# Generated by Django 3.1a1 on 2020-05-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housie', '0002_auto_20200526_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_no',
            field=models.IntegerField(default=0),
        ),
    ]
