# Generated by Django 3.1a1 on 2020-05-27 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housie', '0003_player_player_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_no',
        ),
    ]
